### ISSUE TITLE
Timed effects like Morse code get terminated before they're done

### ISSUE THREAD

**Issue by fhunleth** [smartrent/delux#2]
[Copied from @amclain's report on slack]

> The plot thickens. On a RPI0 for "CQ CQ CQ DE W1AW W1AW K", at 10 WPM it only sends the -. of the K. At 20 WPM it doesn't send the K at all.
> 
> On the mango at 20 WPM I think it sends the whole K.
> 

This is after 5758fe37c432f6289259aa08a3b6c91ec27a5ebf which improved timing somewhat. The problem appears to be due to Elixir and the Linux kernel being out of sync as to when the patterns start playing back.

**Comment by amclain** [comment]
@fhunleth I got some Saleae logic captures for you at 25 WPM. The good news is the timing between dits and dahs looks really good. It's the end of the messages that are getting truncated.

[Delux Morse RPI0.tar.gz](https://github.com/smartrent/delux/files/9311921/Delux.Morse.RPI0.tar.gz)

[Delux Morse MangoPi.tar.gz](https://github.com/smartrent/delux/files/9311922/Delux.Morse.MangoPi.tar.gz)

**Comment by fhunleth** [comment]
@amclain Thanks for the captures. These are super helpful.

Here's what I see:

* Elixir's timing looks good. The requested timeout was 11.904s and the trace shows 11.916s. The extra 12ms could be due to a couple things, but it certainly isn't responsible for cutting off the final "K"
* Dits are 60ms when they should be 48ms
* Dahs are 160ms when they should be 144ms
* The time between words is 350ms when it should be 336ms

It looks like Linux rounds up to the resolution that it can provide. This compounds enough to lengthen the playback of the pattern so that letters get cut off when the Elixir side thinks that it is done.

My understanding is that Linux's playback resolution is the determined by the kernel's timer frequency (under the kernel features menu). For the Raspberry Pi Zero, it's 100 Hz. For the Mango Pi MQ Pro, it's set to 250 Hz. Therefore 10ms vs. 4ms resolution. Linux lets you set the timer frequency to 1000 Hz, so that should be one way of fixing the issue.

I've always set the timer frequency on the embedded systems that I've worked on to 100 Hz and then bumped it if necessary. I had thought that this would be good for power consumption, but I've never verified and I'm getting skeptical whether this would make any difference. 

I do feel like Delux should look at the timer frequency, adjust patterns so that they match what Linux can produce, and adjust the total duration so that the timer that's set on the Elixir side is right.

Could you try modifying the timer frequency on one of your boards to 1000 Hz to see if that fixes the problem? I feel like your traces nailed the issue and verifying that would confirm.

**Comment by amclain** [comment]
Here's a capture of the timer frequency at 1000Hz. The last dah still gets cut off a little, but the issue is significantly better. If the last `binwrite` were pushed out a little, I have a hunch it would fix it. I might be able to try that out if you don't get to it first.

[Delux Morse RPI0 1000Hz.tar.gz](https://github.com/smartrent/delux/files/9330895/Delux.Morse.RPI0.1000Hz.tar.gz)

**Comment by amclain** [comment]
I added a delay after `IO.binwrite` and it did allow the last character to complete. It's probably not the right solution though.

```ex
  defp maybe_write!(handle, data) do
    File.write "/sys/class/gpio/export", "4"
    File.write "/sys/class/gpio/gpio4/direction", "out"
    File.write "/sys/class/gpio/gpio4/value", "1"
    :ok = IO.binwrite(handle, data)
    Process.sleep 100
    File.write "/sys/class/gpio/gpio4/value", "0"
  end
```

Last character finishes:

![image](https://user-images.githubusercontent.com/4755047/184507349-ae7c8832-2c6b-4c43-9ca0-886be7e36e26.png)

Old capture with last character truncated:

![image](https://user-images.githubusercontent.com/4755047/184507388-faaf9a7f-a9fd-4929-870a-8d18622738ff.png)

**Comment by amclain** [comment]
I added trailing padding to the end of the sequence and I'm not seeing the last character get truncated:

[Delux Morse RPI0 1000Hz Trailing Padding 5 WPM.sal.tar.gz](https://github.com/smartrent/delux/files/9388420/Delux.Morse.RPI0.1000Hz.Trailing.Padding.5.WPM.sal.tar.gz)
[Delux Morse RPI0 1000Hz Trailing Padding 25 WPM.sal.tar.gz](https://github.com/smartrent/delux/files/9388421/Delux.Morse.RPI0.1000Hz.Trailing.Padding.25.WPM.sal.tar.gz)
[Delux Morse RPI0 1000Hz Trailing Padding 30 WPM.sal.tar.gz](https://github.com/smartrent/delux/files/9388422/Delux.Morse.RPI0.1000Hz.Trailing.Padding.30.WPM.sal.tar.gz)
